logLevel: info
logDestinations: [stdout]

api: false
metrics: false
pprof: false
playback: false

rtsp: true
rtspAddress: :8554
rtspTransports: [tcp]

rtmp: false
hls: false
webrtc: false
srt: false

paths:
  main-monitor:
    source: publisher
